resource_types:
- name: nomad
  type: docker-image
  source:
    repository: troykinsella/concourse-nomad-resource
    tag: "latest"

resources:
- name: nomad
  type: nomad
  source:
    address: http://localhost:4646
    tag: "latest"
    

- name: concourse-ci 
  type: git 
  icon: github
  source:
    uri: https://github.com/waletaiwo/Concourse-ci.git
    branch: main 
    


jobs:
- name: deploy-to-nomad
  plan:
  - get: concourse-ci # git resource
  - put: nomad # nomad resource 
    params:
      dir: main/concourse-ci 
      job_file: deploy-nomad/nomad.hcl
      job_run: true 